//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTaskData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int SimpleTaskId { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public System.DateTime DueDate { get; set; }
        public int UserId { get; set; }
    }
}
